##############################################
# general config.yml of the GoCraft plugin   #
# dummy file to show the layout              #
# This plugin has been created by NLThijs48  #
##############################################

servers:
  <directory name>:
    id: <id> # To be used in other sections
    name: <display name>
serverGroups:
  <name>: "serverIds, comma-separated"
plugins:
  <name>:
    pushTo: "<server/group, comma-separated>"
    extraFiles: "AsyncWorldEditInjector etc" # TODO