##############################################
# general config.yml of the GoCraft plugin   #
# dummy file to show the layout              #
# This plugin has been created by NLThijs48  #
##############################################

servers:
  <id>:
    directory: <directory name>
    name: <display name>
serverGroups:
  <name>: "serverIds, comma-separated"
plugins:
  <name>:
    pushTo: "<server/group, comma-separated>"