name: GoCraft
main: nl.evolutioncoding.gocraft.GoCraft
version: 1.0
depend: [WorldGuard]
softdepend: [BanManager]
permissions:
  gocraft.*:
    description: Give access to all commands of GoCraft (only for Admins)
    children:
      gocraft.signLog: false
      gocraft.signTell: true
      gocraft.help: true
      gocraft.resetstats: true
      gocraft.resetalll: true
      gocraft.staff: true
      gocraft.update: true
  gocraft.signLog:
    description: Log signs of players with this permission
    default: not op
  gocraft.signTell:
    description: Tell players with this permission placed signs
    default: op
  gocraft.help:
    description: Check the help page with all commands
    default: true
  gocraft.ping:
    description: Check the ping of players.
    default: true
  gocraft.setspawn:
    description: Set the spawn location of the spawnteleport
    default: op
  gocraft.staff:
    description: 'Indicates that this is a staff member, mostly for messages'
    default: op
  gocraft.sendStaffBroadcast:
    description: Send message to all staff on the network.
    default: op
  gocraft.displayStaffMessage:
    description: Display a message to all staff on this server.
    default: op
  gocraft.update:
    description: Update all plugins from the global source
    default: op
commands:
  Ping:
    description: 'Check the ping for a player.'
    usage: 'Go-Craft plugin has not started correctly, contact a staff member.'
    aliases: [p]
  SetGSpawn:
    description: "Set the spawn location of the spawnteleport."
    usage: 'Go-Craft plugin has not started correctly, contact a staff member.'
  StaffBroadcast:
    description: Send message to all staff on the network.
    usage: 'Go-Craft plugin has not started correctly, contact a staff member.'
  DisplayStaffMessage:
    description: Display a message to all staff on this server.
    usage: 'Go-Craft plugin has not started correctly, contact a staff member.'
  Update:
    description: 'Update plugins from global source.'
    usage: 'Go-Craft plugin has not started correctly, contact a staff member.'