##############################################
# config.yml of the GoCraft plugin, settings for this plugin
##############################################

########## OPTIONS
chatPrefix: "&2[Go-Craft]&r "
debug: false
language: EN
useFancyMessages: true
worlds:
# <worldname>:
#   radius: <number>
#   resetTime: <duration>

########## CURRENCY
moneyCharacter: '€'
moneyCharacterAfter: ''
fractionalNumbers: 2
hideEmptyFractionalPart: true
metricSuffixesAbove: 1000000.0
decimalMark: '.'

########## BLOCKS
disableBlockBreaking: false
disableBedrockBreak: true
disableBedrockPlace: true
disableDispensers: false
disableTradeSignPlacing: false
disableAnvilBreak: false
disableWitherDamage: false

########## GENERAL
disableRain: false
disableMobSpawning: false
disableHungerLoss: false
enablePotionEffectsOnJoin: false
potionEffectsOnJoin:
enableRegionPotionEffects: false
regionPotionEffects:
spawnTeleport: false
enableInspecting: true
disableOpenEnderSelf: true
disableSignUseWhileMuted: true
clickChatMessages: true
disableFrostWalker: false

########## ITEMS
disableItemDrops: false
disableItemSpawning: false
disablePotionSplash: false
disablePotionThrow: false
disablePotionInvisibleDrink: false
disableXpBottleThrow: false
disableFirework: false
disableEnderpearl: false
disableEyeOfEnder: false
disableBooks: false

########## LOGGING
signLoggingEnabled: true
signLogTimeFormat: 'dd-MM-yyyy HH:mm:ss'

########## PVP
disablePlayerDamage: false
disableFallDamage: false
oldHunger: false

########## OTHER
disableAboveNetherGlitching: false
enableAddDefaultRank: false
enablePunishmentNotifications: true
disableVoidFall: false
commandSyncEnabled: true
commandSyncPort: 9191 # CommandSync uses 9190, but we don't want to clash with that
collectVotes: false
showVoteScoreboard: false

spawnPoints:
  enable: false
  randomizeDirection: true
  regions: # whitelist of regions where you can use the /respawn command
  dynmapMarkerIcon: down

########## Combat
auracheck:
  enablePeriodicCheck: true
  ## Seconds between checking all players on the server for killaura (range)
  periodicIntervalMin: 60
  periodicIntervalMax: 120
  ## Ticks before going on with the next player
  playerIntervalTime: 5
  ## Hacks detected threshold
  hacksConfirmed: 3
  ## Send warning to staffchat
  staffChatWarning: 2
  ## Log a message to console with this much kills
  consoleLogging: 1
  ticksToKill: 10
  numberOfFakePlayers: 4
  visiblePlayers: false
hacksConfirmedCommand: "hackban %player% %reason%"
staffJoinsInInspect: false
enableNauseaPotions: true
playerAttributes: # Set player attributes
# generic_attack_speed: 12 # 4 is 1.9 PVP, 16 is 1.8 PVP

rewards:
# <key>:
#    permission: <string> # Permission node
#    ranks: <string> # List or single rank
#    uuids: <string> # List or single UUID
#    commands: <string> # List or single command (has %player% and %uuid%)
#    message: <plain message or fancy>

shop:
# categories:
#   <key>:
#     name:
#     button: <item>
# kits:
#   <key>:
#     name:
#     price:
#     cooldown:
#     button: <item>
#     categories: <comma separated list>
#     items: <item>
#     items:
#       - <item>
