##############################################
# config.yml of the GoCraft plugin           #
# This plugin has been created by NLThijs48  #
##############################################

########## OPTIONS
chatPrefix: "&2[Go-Craft]&r "
debug: true

########## CURRENCY
moneyCharacter: '%euro%'
moneyCharacterAfter: ''
fractionalNumbers: 2
hideEmptyFractionalPart: true
metricSuffixesAbove: 1000000.0
decimalMark: '.'

########## BLOCKS
disableBlockBreaking: false
disableBedrockBreak: true
disableBedrockPlace: true
disableDispensers: false
disableTradeSignPlacing: false
disableAnvilBreak: false
disableWitherDamage: false

########## GENERAL
disableRain: false
disableMobSpawning: false
disableHungerLoss: false
enablePotionEffectsOnJoin: false
potionEffectsOnJoin:
enableRegionPotionEffects: false
regionPotionEffects:
spawnTeleport: false
enableInspecting: true
disableStaffJoinLeaveMessages: true
disableOpenEnderSelf: true
disableSignUseWhileMuted: true

########## ITEMS
disableItemDrops: false
disableItemSpawning: false
disablePotionSplash: false
disablePotionThrow: false
disablePotionInvisibleDrink: false
disableXpBottleThrow: false
disableFirework: false
disableEnderpearl: false
disableEyeOfEnder: false
disableBooks: false

########## LOGGING
signLoggingEnabled: true
signLogTimeFormat: 'dd-MM-yyyy HH:mm:ss'

########## PVP
disablePlayerDamage: false
disableFallDamage: false

########## COMMANDS
redirectTempban: true
changePrivateMessages: true
enablePingCommand: true
enableStaffMessageCommands: true
enableUpdateCommand: true
enableReloadCommand: true
enableRulesCommand: true
enableHelpCommand: true

########## OTHER
enableExpiredPlotsRestoration: false
disableAboveNetherGlitching: false
enableAddDefaultRank: false
worlds:
# <worldname>:
#   radius: <number>
#   resetTime: <duration>

########## AURACHECK
## Automatic aura checking (fake player spawning and hit detection)
auracheck:
  enablePeriodicCheck: true
  ## Seconds between checking all players on the server for killaura (range)
  periodicIntervalMin: 60
  periodicIntervalMax: 120
  ## Ticks before going on with the next player
  playerIntervalTime: 5
  ## Hacks detected threshold
  hacksConfirmed: 3
  ## Send warning to staffchat
  staffChatWarning: 2
  ## Log a message to console with this much kills
  consoleLogging: 1
  ticksToKill: 10
  numberOfFakePlayers: 4
  visiblePlayers: false

hacksConfirmedCommand: "gopvp:hackban %player% %reason%"
staffJoinsInInspect: false
enableNauseaPotions: true

rewards:
# <key>:
#    target:
#      - "rank:<>, uuid:<>" # rank matches and uuid matches
#      - "" # Or this line matches
#    commands:
#      - "/eco give %player% 500"
#    message: <plain message or fancy>
#      - ""

shop:
# categories:
#   <key>:
#     name:
#     button: <item>
# kits:
#   <key>:
#     name:
#     price:
#     cooldown:
#     button: <item>
#     categories: <comma separated list>
#     items: <item>
#     items:
#       - <item>
