##############################################
# general config.yml of the GoCraft plugin   #
# dummy file to show the layout              #
# This plugin has been created by NLThijs48  #
##############################################

# Server settings
servers:
  <id>:
    directory: <directory name>
    name: <display name>
# Server groups
serverGroups:
  <name>: "serverIds, comma-separated"
# Rules
rules:
  <servers>:
    - rules
# Help
help:
  <servers>:
    - help
# Root files
rootfiles:
  <name>:
    pushTo: ""
    source: "<filename>"
    target: "<filename>"
  <name>: "<servers>"

# Plugin files
plugins:
  <name>:
    pushTo: "<server/group, comma-separated>"
    permissions:
      <name>:
        servers: <servers>
        groups: <ranks>
        permissions: <single or list>
        help: <single or list>