name: GoCraft
main: me.wiefferink.gocraft.GoCraft
version: 1.0
softdepend: [BanManager, WorldGuard, Vault, MapSwitcher, Essentials, dynmap, ProtocolLib]
author: NLThijs48
website: http://go-craft.com
permissions:
  gocraft.*:
    description: Give access to all commands of GoCraft (only for Admins)
    children:
      gocraft.signLog: false
      gocraft.signTell: true
      gocraft.help: true
      gocraft.resetstats: true
      gocraft.resetalll: true
      gocraft.staff: true
      gocraft.update: true
      gocraft.reload: true
  gocraft.signLog:
    description: Log signs of players with this permission
    default: not op
  gocraft.signTell:
    description: Tell players with this permission placed signs
    default: op
  gocraft.help:
    description: Check the help page with all commands
    default: true
  gocraft.ping:
    description: Check the ping of players.
    default: true
  gocraft.rules:
    description: Check the rules on the server
    default: true
  gocraft.help:
    description: Check the help page
    default: true
  gocraft.setspawn:
    description: Set the spawn location of the spawnteleport
    default: op
  gocraft.staff:
    description: 'Indicates that this is a staff member'
    default: op
  gocraft.sendStaffBroadcast:
    description: Send message to all staff on the network.
    default: op
  gocraft.displayStaffMessage:
    description: Display a message to all staff on this server.
    default: op
  gocraft.update:
    description: Update all plugins from the global source
    default: op
  gocraft.reload:
    description: Reload the plugin data
    default: op
  gocraft.joinInInspect:
    description: Join in inspect mode
    default: op
  gocraft.shop:
    description: Allows you to open and use the shop
    default: op
  gocraft.placeKitSign:
    description: Allows you to place kit shop signs
    default: op
  gocraft.placeShopSign:
     description: Allows you to place shop signs
     default: op
  gocraft.auracheck:
    description: Check if a player has kill aura hacks
    default: op
  gocraft.randomtp:
    description: Randomly teleport in the world
    default: op