name: GoCraft
main: me.wiefferink.gocraft.GoCraft
version: "${timestamp}"
softdepend: [BanManager, WorldGuard, Vault, MapSwitcher, Essentials, dynmap, ProtocolLib]
author: NLThijs48
website: http://go-craft.com